# Networking config
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_HOSTNAME_DYNAMIC=y
CONFIG_TEST_RANDOM_GENERATOR=y

# DNS
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_RESOLVER_AUTO_INIT=y
CONFIG_DNS_RESOLVER_ADDITIONAL_QUERIES=2
CONFIG_DNS_RESOLVER_MAX_SERVERS=2

# DHCP configuration.
CONFIG_NET_DHCPV4=y
#CONFIG_NET_DHCPV6=y
# Recommended for WiFi APs
CONFIG_NET_DHCPV4_SERVER=y
#CONFIG_NET_DHCPV6_SERVER=y

# Required for socket.pkt_get_info()
CONFIG_NET_BUF_POOL_USAGE=y

# Do provide a decent amount of zephyr heap, yet less than recommended if often enough:
# Most features won't be used all at the same time
#CONFIG_HEAP_MEM_POOL_SIZE=32768
#CONFIG_HEAP_MEM_POOL_IGNORE_MIN=y

# Enable heap statistics module to watch out for issues
#CONFIG_SYS_HEAP_RUNTIME_STATS=y

# Required for zephyr.shell_exec("net iface")
#CONFIG_NET_SHELL=y

# Uncomment to enable "INFO" level net_buf logging
#CONFIG_NET_LOG=y
#CONFIG_NET_DEBUG_NET_BUF=y
# Change to 4 for "DEBUG" level
#CONFIG_SYS_LOG_NET_LEVEL=3

# Don't use a ton of RAM for nothing
#CONFIG_MBEDTLS_PSA_STATIC_KEY_SLOTS=n
